// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {PriceMath} from "@/math/PriceMath.sol";
import {CurveMath} from "@/math/CurveMath.sol";
import {CurveShape} from "@/SlopeTypes.sol";
import {IAquaSwapVMRouter} from "@/interfaces/IAquaSwapVMRouter.sol";

/// @dev Cross-validation: the committed vectors are generated by the
/// TypeScript reference model (shared/scripts/generate-vectors.ts) and must
/// match the Solidity kernel bit-for-bit, including the WETH(18)/USDC(6)
/// asymmetric-decimals case (docs/MATH_SPEC.md section 7).
contract CurveVectorsTest is Test {
    string internal constant VECTORS = "test/vectors/curve-vectors.json";

    function test_ProgressVectorsMatchTheReferenceModel() external view {
        string memory json = vm.readFile(VECTORS);
        uint256[] memory elapsed = vm.parseJsonUintArray(json, ".elapsed");
        uint256[] memory duration = vm.parseJsonUintArray(json, ".duration");
        uint256[] memory expected = vm.parseJsonUintArray(json, ".expectedProgress");
        assertEq(elapsed.length, duration.length);
        assertEq(elapsed.length, expected.length);
        for (uint256 i = 0; i < elapsed.length; i++) {
            assertEq(
                CurveMath.progress(elapsed[i], duration[i], CurveShape.NEUTRAL),
                expected[i],
                "progress vector mismatch"
            );
        }
    }

    function test_PriceVectorsMatchTheReferenceModel() external view {
        string memory json = vm.readFile(VECTORS);
        uint256[] memory amountOut = vm.parseJsonUintArray(json, ".pAmountOut");
        uint256[] memory decimalsOut = vm.parseJsonUintArray(json, ".pDecimalsOut");
        uint256[] memory amountIn = vm.parseJsonUintArray(json, ".pAmountIn");
        uint256[] memory decimalsIn = vm.parseJsonUintArray(json, ".pDecimalsIn");
        uint256[] memory expected = vm.parseJsonUintArray(json, ".pExpected");
        assertEq(amountOut.length, expected.length);
        for (uint256 i = 0; i < amountOut.length; i++) {
            (bool ok, uint256 price) =
                PriceMath.tryNormalizePrice(amountOut[i], uint8(decimalsOut[i]), amountIn[i], uint8(decimalsIn[i]));
            assertTrue(ok);
            assertEq(price, expected[i], "price vector mismatch");
        }
    }
}

/// @dev Step-3 compatibility gate: our minimal interface must stay
/// selector-compatible with the deployed official router (tag v1.0.2).
contract InterfaceSelectorsTest is Test {
    function test_SwapSelectorMatchesOfficialAquaRouter() external pure {
        assertEq(IAquaSwapVMRouter.swap.selector, bytes4(0xf4d2d412));
    }

    function test_QuoteSelectorMatchesOfficialAquaRouter() external pure {
        assertEq(IAquaSwapVMRouter.quote.selector, bytes4(0x44aa5f14));
    }
}
